apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: g2aen3aml-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-fd4b9b8a19.zthc.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:0a510174eb8f4d6758a84ca6e8a5244f41cca61c@sha256:6030aa97efc2ae4eaefdfee3d9c1f8ef3f72cb38d045b57588c37d749127b20c
          name: container-image
